In [35]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
import numpy as np
from Implementations import *
from Implementations_helpers import *
from proj1_helpers import *
from Cross_validation import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [41]:
def Hyperparameter_optimization(y, tx, k_fold, lambdas , gammas, initial_w =1, max_iters = 100, model = 'least_squares'):
    """optimize the hyperameters for correspongding model/algorithm
    lambdas: the range of lambda_
    gammas: the range of gamma
    
    """
    accuracies = np.zeros((len(lambdas), len(gammas)))
    for index_lambda_, lambda_ in enumerate(lambdas):
        for index_gamma, gamma in enumerate(gammas):
            _, accuracy = cross_validation(y, tx, k_fold, lambda_, gamma, initial_w.copy(), max_iters, model)
            accuracies[index_lambda_,index_gamma] = accuracy
    optimal_index = np.unravel_index(accuracies.argmax(), accuracies.shape)
    optimal_lambda_, optimal_gamma = lambdas[optimal_index[0]], gammas[optimal_index[1]]
    optimal_accuracy = accuracies.max()
    
    print("Model: {0} \n Optimal accuracy: {1} \n Optimal lambda_: {2} \n Optimal gamma: {3} \n ".format(
          model, optimal_accuracy, optimal_lambda_, optimal_gamma))
    
    return optimal_accuracy, optimal_lambda_, optimal_gamma
    
            
    

In [30]:
y = np.random.rand(100000).reshape((100000,1))
y[np.where(y <= 0.5)] = 0
y[np.where(y > 0.5)] = 1
tx = np.c_[y-1,y+1]
weight = np.zeros((tx.shape[1], 1)) + 0.5
weight = weight*0.5
lambdas = [0]#np.linspace(0,1,5)
gammas = np.logspace(-2,-1,5) # np.logspace
max_iters = 100
k_fold = 5
gamma = 0.1
seed = 2

In [43]:
weight

array([[0.25],
       [0.25]])

In [44]:
Hyperparameter_optimization(y, tx, k_fold, lambdas , gammas, initial_w = weight, max_iters = 10, model = 'least_squares_GD')

 Model least_squares_GD 
 Loss: 0.04875314534003825 
 Accuracy: 1.0
 Model least_squares_GD 
 Loss: 0.03369153002602601 
 Accuracy: 1.0
 Model least_squares_GD 
 Loss: 0.0191735022054157 
 Accuracy: 1.0
 Model least_squares_GD 
 Loss: 0.010143044530900888 
 Accuracy: 1.0
 Model least_squares_GD 
 Loss: 0.0064679929874918605 
 Accuracy: 1.0
Model: least_squares_GD 
 Optimal accuracy: 1.0 
 Optimal lambda_: 0 
 Optimal gamma: 0.01 
 


(1.0, 0, 0.01)

In [45]:
weight

array([[0.25],
       [0.25]])

In [46]:
least_squares_GD(y, tx, weight, 10, 0.5)

(0.00044374872685001946, array([[0.44643957],
        [0.49271194]]))

In [47]:
weight

array([[0.25],
       [0.25]])

In [48]:
cross_validation(y, tx,5, 0, 1e-10, weight, 20, 'least_squares_GD')

 Model least_squares_GD 
 Loss: 0.08124999914687492 
 Accuracy: 1.0


(0.08124999914687492, 1.0)

In [49]:
weight

array([[0.25],
       [0.25]])