In [13]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from Hyperparameter_optimization import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
feature_names = load_headers(DATA_TRAIN_PATH)

# convert y from -1/1 to 0,1
y = (y+1)/2

In [11]:
from preprocess_data import *

data_pro  = data_preprocess_train(tX,y,outlier_method = 'IQR',n_out = 3)

for i in range(6):
    print(data_pro[i][1])

[0. 0. 0. ... 1. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 1. ... 0. 1. 1.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 1. ... 1. 1. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [49]:
from Hyperparameter_optimization import *

In [64]:
lambda_ = [0]
gamma_ = [1e-4]
accuracy_ = []
group_size_ = []
for idx_data,data in enumerate(data_pro):
    print('┌'+'─' * 38+'┐')
    print('│               Group: %i               │'%idx_data)
    print('└'+'─' * 38+'┘')
    tx = data[0]
    y = data[1]
    initial_w_ = np.ones(tx.shape[1])
    optimal_accuracy, optimal_lambda_, optimal_gamma = Hyperparameter_optimization( y, tx,k_fold=4, 
                                                                                   lambdas=lambda_ , 
                                                                                   gammas = gamma_, 
                                                                                   initial_w = initial_w_, 
                                                                                   max_iters = 1000, 
                                                                                   model = 'ridge_regression')
    accuracy_.append(optimal_accuracy)
    group_size_.append(len(data[2]))

accuracy_all = np.dot(accuracy_,group_size_)/np.sum(group_size_)
print('\n * Overall Accuracy = %.4f'%accuracy_all)

┌──────────────────────────────────────┐
│               Group: 0               │
└──────────────────────────────────────┘
────────────────────────────────────────
lambda : 0,  gamma: 0.0001 
 
 Model ridge_regression 
 Loss: 0.13134087391240726 
 Accuracy: 0.6929717569252453
════════════════════════════════════════
*The optimal hyperparameters*:
 Model: ridge_regression 
 Optimal accuracy: 0.6929717569252453 
 Optimal lambda_: 0 
 Optimal gamma: 0.0001 
 
┌──────────────────────────────────────┐
│               Group: 1               │
└──────────────────────────────────────┘
────────────────────────────────────────
lambda : 0,  gamma: 0.0001 
 
 Model ridge_regression 
 Loss: 0.026579363200754248 
 Accuracy: 0.9403139356814703
════════════════════════════════════════
*The optimal hyperparameters*:
 Model: ridge_regression 
 Optimal accuracy: 0.9403139356814703 
 Optimal lambda_: 0 
 Optimal gamma: 0.0001 
 
┌──────────────────────────────────────┐
│               Group: 2            

In [39]:
accuracy_all = np.dot(accuracy_,group_size_)/np.sum(group_size_)
print('Overall Accuracy = %.4f'%accuracy_all)

Overall Accuracy = 0.6666


In [27]:
cross_validation( y= data_pro[1][1], tx = data_pro[1][0],k_fold=4, lambda_ = 0.1, gamma = 0.7, initial_w =1, max_iters = 100, model =  'ridge_regression')

 Model ridge_regression 
 Loss: 0.026687801163996223 
 Accuracy: 0.9403139356814703


(0.026687801163996223, 0.9403139356814703)